---
- name: exists?
  shell: command -v zsh
  register: zsh
  ignore_errors: yes
- name: install
  homebrew:
    name: zsh
    update_homebrew: yes
    upgrade_all: yes
  when: zsh.stdout != "/usr/local/bin/zsh"
- name: default shell
  shell: dscl . -create "/Users/$USER" UserShell /usr/local/bin/zsh
  become: true
- name: source .machine
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.zshrc"
    create: yes
    line: source $HOME/.machine
