---
- name: exists?
  shell: command -v brew >/dev/null 2>&1
  register: brew
  ignore_errors: yes
- name: install
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: brew.rc != 0
- name: update
  homebrew:
    update_homebrew: yes
- name: upgrade formula
  homebrew:
    upgrade_all: yes
- name: upgrade casks
  homebrew_cask:
    greedy: yes
    upgrade_all: yes
- name: path
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.machine"
    create: yes
    line: "{{ item }}"
  loop:
    - export PATH="/usr/local/bin:$PATH"
    - export PATH="/usr/local/sbin:$PATH"
- name: taps
  homebrew_tap:
    name: "{{ item }}"
  loop:
    - homebrew/cask-drivers
    - homebrew/command-not-found
