---
- name: clone
  git:
    repo: git@github.com:sugarcrm/multiverse.git
    dest: "{{ lookup('env','HOME') }}/go/src/github.com/sugarcrm/multiverse"
    update: no
    remote: upstream
  register: cloned
- name: add origin
  command: git remote add origin git@github.com:{{ github_username }}/multiverse.git
  args:
    chdir: "{{ lookup('env','HOME') }}/go/src/github.com/sugarcrm/multiverse"
  when: cloned.before == None
- name: fetch origin
  command: git fetch origin
  args:
    chdir: "{{ lookup('env','HOME') }}/go/src/github.com/sugarcrm/multiverse"
  when: cloned.before == None
  ignore_errors: yes
- name: integrated tooling
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.machine"
    create: yes
    line: export PATH="$PATH:{{ lookup('env','HOME') }}/go/src/github.com/sugarcrm/multiverse/tools/bin"
- name: auto-completion
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.machine"
    create: yes
    line: source {{ lookup('env','HOME') }}/go/src/github.com/sugarcrm/multiverse/tools/completion.bash
